### ISSUE TITLE
Frozen columns BUG

### ISSUE THREAD

**Issue by szeplaszloit** [vaadin/tree-grid#14]
I try to use setFrozenColumnCount(1); but it doesn't work (v 0.7.3).

I would like to freeze only the first, hierarchy column. I disabled the built-in selection checkbox column. I tested with values: -1;0;1, but has no effect. With value 2 the first two columns wil be frozen.

**Comment by wbadam** [comment]
Hi, this issue was addressed in #7, are you certain you are using the newest 0.7.3 release?

By
> I disabled the built-in selection checkbox column

do you mean that you are setting `grid.setSelectionMode(Grid.SelectionMode.SINGLE);` or `grid.setSelectionMode(Grid.SelectionMode.NONE);`?
For me, freezing columns work with all selection modes.

**Comment by szeplaszloit** [comment]
Hi,

thanks for a reply. Yes, I'm sure, I'm using the v0.7.3 release.

I'm setting the selection mode to NONE, but I think, it doesn't matter. Without an explicit definition also doesn't work.

My code is simple:

```
TreeGrid grid = new TreeGrid();

grid.setSizeFull();
grid.setColumnReorderingAllowed(false);
grid.setEditorEnabled(false);
grid.setSelectionMode(Grid.SelectionMode.NONE);
grid.setCellStyleGenerator(...);
grid.setContainerDataSource(...);
grid.setHierarchyColumn(...);

// Add some extra header rows...
for (...) {
	grid.prependHeaderRow();
}

grid.setFrozenColumnCount(1);
```

I don't understand what I'm doing wrong.

**Comment by wbadam** [comment]
Right, I think you need to set column reordering to `true` instead of `false` with
<pre>grid.setColumnReorderingAllowed(<b>true</b>);</pre>
and then you can tell with `grid.setFrozenColumnCount();` how many columns you would like to freeze.

**Comment by szeplaszloit** [comment]
hmmm, thank you, that's interesting

I set column reordering to `true`, and it's still not working, BUT if I reorder the columns manually, it will suddenly start to work :D

Of course, I don't need a column reordering function, so I'm still looking for a solution...

**Comment by wbadam** [comment]
Of course, you don't need to allow column reordering, sorry. Frozen column is prevented from reordering as well, that was in my mind.

Your issue does seem very much like #7 that was fixed in 0.7.3. I suggest you try deleting com/vaadin/vaadin-treegrid from your local maven repository and try building your application again and see if that helps or if indeed the correct version is downloaded.

**Comment by Snap252** [comment]
> Your issue does seem very much like #7 that was fixed in 0.7.3.

Sorry, bad news - it seems not to be fixed 100% - after a rebuild of the columns it happens again. But I had no time to take a deeper look at it

**Comment by wbadam** [comment]
Could you please send a simple app as an example? I can't seem to reproduce the issue.

**Comment by Snap252** [comment]
I tried all the weekend to make it simple reproducable ... but seems not to be easy without publishing all my application.

It seems to happen when removing a column while adding rows within same request.

It seems to depend on the ComplexRenderer that replaces the default renderer (even it is a Buttonrenderer - so it does not depend on the HierarchyRenderer) - with a normal text renderer that replaces the old renderer, there is no such problem.

Is it really good to wrap the underlying renderer on client instead of doing this server side - maybe the grid supports this some better?

**Comment by szeplaszloit** [comment]
For me, already works fine. Just downloaded the source code directly from github, and it works.

**Comment by Snap252** [comment]
Another 2 days spent....

- I have the case where I remove columns and add rows within the same request
- The columns are refreshed(recreated) first by an internal vaadin mechanism, that is no problem because no rows are re-rendered
- When your addon detects a column change then you wrap the original renderer of the column and set it to the column
- That forces the grid to refresh its rows that have not been updated 
Setting the renderer server side explicitly to one column fixes the problem for me (of cause the server side part is missing in the main branch - I think I will send you a suggestion)

But it does not look like this is the original problem of the issue.

**Comment by wbadam** [comment]
Hi,

First of, thanks for trying to find the cause of the issue.

I tried reproducing a few weeks back by removing columns and adding rows at the same time as you suggested but without any luck, I didn't seem to be able to reproduce.

Are you having problems when you are building the add-on from master?
